package net.serenitybdd.cucumber.adapter

import net.thucydides.core.model.TestOutcome
import net.thucydides.core.model.TestResult
import spock.lang.Specification
/**
 * Uses a cucumber json file generated by
 * @see net.serenitybdd.cucumber.integration.SimpleTableScenario
 */
class WhenImportingCucumberJsonFilesWithExamples extends Specification {
    def "it should have a scenario per example table and child steps for each example row"() {
        given:
        def adapter = new CucumberJsonAdapter();
        when:
        def outcomes = adapter.loadOutcomesFrom(new File("src/test/resources/cucumber-json-files/SimpleTableScenario.json"))
        then:
        outcomes.size() == 2
        outcomes[0].testSteps.size() == 7
        outcomes[0].testSteps[0].children.size() == 5
        outcomes[0].testSteps[3].children.size() == 5
        outcomes[0].testSteps[6].children.size() == 5
        outcomes[1].testSteps.size() == 3
        outcomes[1].testSteps[0].children.size() == 5
        outcomes[1].testSteps[2].children.size() == 5
    }

}

